import { mkdir } from "node:fs/promises";
import { resolve } from "node:path";
import { createHash } from "node:crypto";
import dictionary from "../apps/keytest/assets/voice/speech.json";
import config from "../apps/keytest/assets/voice/kokoro.json";
import { readVoiceWav } from "./voice-wav";

const root = resolve(import.meta.dir, "..");
export async function writeSpeechIndex(check = false) {
  const dir = resolve(root, "apps/keytest/assets/voice/clips");
  const manifest = await Bun.file(resolve(dir, "manifest.json")).json();
  if (Object.entries(config).some(([key, value]) => manifest[key] !== value)) throw new Error("Speech config mismatch");
  const ids = new Set<string>();
  const characters = new Set<string>();
  const controls = new Set<string>();
  const groups = new Map<string, Buffer[]>();
  const lines = ["// Generated by just voice-index from assets/voice/speech.json. Do not hand-edit.",
    'pub const Clip = struct { id: []const u8, spoken: []const u8, characters: []const u16, control: ?[]const u8, wav: []const u8 };',
    'pub const clips = [_]Clip{'];
  for (const entry of dictionary) {
    if (!/^[a-z0-9-]+$/.test(entry.id) || ids.has(entry.id)) throw new Error(`Invalid/duplicate speech ID: ${entry.id}`);
    ids.add(entry.id);
    for (const char of entry.characters ?? "") {
      if (characters.has(char)) throw new Error(`Duplicate speech character: ${char}`);
      characters.add(char);
    }
    if (entry.control) {
      if (controls.has(entry.control)) throw new Error(`Duplicate speech control: ${entry.control}`);
      controls.add(entry.control);
    }
    const wav = Buffer.from(await Bun.file(resolve(dir, `${entry.id}.wav`)).arrayBuffer());
    const { samples, rate } = readVoiceWav(wav);
    const clip = manifest.clips.find((clip: any) => clip.id === entry.id);
    if (!clip || clip.spoken !== entry.spoken || clip.prompt !== `${entry.pronunciation ?? entry.spoken}.` || clip.seconds !== samples.length / rate ||
        clip.sha256 !== createHash("sha256").update(wav).digest("hex")) throw new Error(`Stale speech asset: ${entry.id}`);
    const chars = [...(entry.characters ?? "")].map(c => c.charCodeAt(0));
    lines.push(`    .{ .id = "${entry.id}", .spoken = ${JSON.stringify(entry.spoken)}, .characters = &.{ ${chars.join(", ")} }, .control = ${entry.control ? JSON.stringify(entry.control) : "null"}, .wav = @embedFile("assets/voice/clips/${entry.id}.wav") },`);
    const group = groups.get(entry.group) ?? [];
    group.push(wav);
    groups.set(entry.group, group);
  }
  if (manifest.clips.length !== dictionary.length) throw new Error("Unexpected speech manifest entries");
  lines.push("};", "");
  const index = resolve(root, "apps/keytest/speech-data.zig");
  // Use the repository's pinned Zig formatter so format checks stay reproducible.
  const format = Bun.spawn(["zig", "fmt", "--stdin"], { stdin: new Blob([lines.join("\n")]), stdout: "pipe", stderr: "pipe" });
  const formatted = await new Response(format.stdout).text();
  if (await format.exited !== 0) throw new Error(await new Response(format.stderr).text());
  if (check) {
    if (await Bun.file(index).text() !== formatted) throw new Error("Stale speech-data.zig; run just voice-index");
    return;
  }
  await Bun.write(index, formatted);
  await mkdir(resolve(root, "artifacts/speech"), { recursive: true });
  for (const [group, wavs] of groups) {
    const data = Buffer.concat(wavs.flatMap(wav => [wav.subarray(44), Buffer.alloc(24000)]));
    const header = Buffer.from(wavs[0].subarray(0, 44));
    header.writeUInt32LE(data.length + 36, 4);
    header.writeUInt32LE(data.length, 40);
    await Bun.write(resolve(root, `artifacts/speech/${group}.wav`), Buffer.concat([header, data]));
  }
  console.log(`Indexed ${dictionary.length} speech clips; audition reels are in artifacts/speech/.`);
}

if (import.meta.main) await writeSpeechIndex(process.argv.includes("--check"));
